[tool.black]
line-length = 88
exclude = '''
/(
    \.git
  | \.idea
  | \.pytest_cache
  | \.ve.*
  | \.coverage
  | \.DS_Store
  | \.testmondata
  | \.vscode
  | \.idea
  | \__pycache__
  | \__MACOSX
  | \.~lock\..*
  | .*\.pyc
  | .*\.swo
  | docs
  | node_modules
  | dashboard
  | htmlcov
  | client
  | temp
  | ls_tmp
  | scratch
  | mocker
  | prof
  | virtualenv
  | src/wrong_main.py
)/
'''

