[tool.black]
line-length = 88
exclude = '''

(
  /(
      \.git
    | \.idea
    | \.github
    | \.pytest_cache
    | \.ve.*
    | \.coverage
    | \.DS_Store
    | \.testmondata
    | \.vscode
    | \.idea
    | \__pycache__
    | \__MACOSX
    | \.~lock\..*
    | .*\.pyc
    | .*\.swo
    | docs
    | node_modules
    | dashboard
    | htmlcov
    | client
    | temp
    | ls_tmp
    | scratch
    | mocker
    | prof
    | virtualenv
  )/
  | other.py
)
'''

