# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Linter/Style Checker

on:
  push:
    branches:
    - master
    - main
    - next
  pull_request:
jobs:
  build:
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        echo ${{ github.event.pull_request.base.ref }}
        echo ${{ github.event.pull_request.head.ref }}
        git fetch origin
        echo "FETCHED origin"
        git branch -r
        BASE_BRANCH=origin/${{ github.event.pull_request.base.ref }}
        echo $(git diff --name-only --diff-filter=b $(git merge-base HEAD $BASE_BRANCH))
        DIFF=$(git diff --name-only --diff-filter=b $(git merge-base HEAD $BASE_BRANCH))
        echo $DIFF
