# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Linter/Style Checker

on:
  push:
    branches:
    - master
    - main
    - next
  pull_request:
jobs:
  build:
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Gather Added/Modified Files
      run: |
        git fetch origin
        git branch -r
        AFTER_HASH=${{ github.event.pull_request.head.sha }}
        BEFORE_HASH=${{ github.event.pull_request.base.sha }}
        if [ $AFTER_HASH == "" ]
        then
            AFTER_HASH=github.event.push.after
        fi
        if [ $BEFORE_HASH == "" ]
        then
            BEFORE_HASH=github.event.push.before
        fi

        AFTER_HASH=${{ github.event.pull_request.head.sha }}
        BEFORE_HASH=${{ github.event.pull_request.base.sha }}
        FILES_ADDED_MODIFIED=$(git diff --name-only --diff-filter=b $(git merge-base $AFTER_HASH $BEFORE_HASH))
        echo "FILES_ADDED_MODIFIED=$FILES_ADDED_MODIFIED" >> $GITHUB_ENV
    - name: ECHO DEPENDENCIES
      run: |
        echo "${{ env.FILES_ADDED_MODIFIED }}"
