# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Linter/Style Checker

on:
  push:
    branches:
    - master
    - main
    - next
  pull_request:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get branch name (merge)
      if: github.event_name != 'pull_request'
      shell: bash
      run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
    - name: Get branch name (pull request)
      if: github.event_name == 'pull_request'
      shell: bash
      run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV
    - name: Debug
      run: echo ${{ env.BRANCH_NAME }}
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
    - name: Get ADDED_OR_CHANGED_FILES
      shell: bash
      run: |
        ADDED_OR_CHANGED_FILES=$(git diff --name-only --diff-filter=b $(git merge-base HEAD $BRANCH))
        echo "BRANCH_NAME=$ADDED_OR_CHANGED_FILES" >> $GITHUB_ENV
    - name: Setup flake8 annotations
      uses: rbialon/flake8-annotations@v1
    - name: Lint with flake8
      run: |
        # Echo ADDED_OR_CHANGED_FILES
        echo ${{ env.ADDED_OR_CHANGED_FILES }}
        # Echo env.BRANCH_NAME
        echo ${{ env.BRANCH_NAME }}
        # Echo BRANCH
        echo $BRANCH
        # Getting only changed/added files
        DIFF=$(git diff --name-only --diff-filter=b $(git merge-base HEAD $BRANCH))
        #ECHO DIFF
        echo $DIFF
        # stop the build if there are Python syntax errors or undefined names
        flake8 $DIFF --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 $DIFF --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Black Check
      run: |
        set -eax
        black --version
        black . --check
    - name: Test with pytest
      run: |
        pytest
